# Generated by Django 3.1.3 on 2020-11-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20201125_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Название ЯП', 'verbose_name_plural': 'Названия языков'},
        ),
    ]
