# Generated by Django 3.1.3 on 2020-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_vacancy_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
    ]
